### ISSUE TITLE
Der Punkt löscht die Eingabe

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#10]
Wenn man bei der Anzahl einen Punkt eingibt wird das gesamte Feld geleert. Sowohl im Bedarf erstellen als auch im Angebot erstellen.

**Comment by skyrun2001** [comment]
Nicht nur der Punkt löscht die Eingabe der Anzahl. Auch folgende Tasten:

- Plus

- Mal

- Geteilt

- Raute

Weitere Tasten konnte ich noch nicht testen.

**Comment by alex-praschek** [comment]
Funktioniert, ist aber noch nicht gepusht
