### ISSUE TITLE
Datum aus der Vergangenheit

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#11]
Bei der Haltbarkeit ist es möglich Daten aus der Vergangenheit einzugeben. 
![image](https://user-images.githubusercontent.com/59117040/78370539-10dbbf80-75c7-11ea-865a-224e2547049a.png)

**Comment by alex-praschek** [comment]
Alles in der Vergangenheit ist ab sofort deaktiviert
