### ISSUE TITLE
Schreiben Sie uns eine Email als Link

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#12]
![image](https://user-images.githubusercontent.com/59117040/78370985-ad05c680-75c7-11ea-811d-721baef88ab9.png)

Ist es möglich, dies als Link zu machen, dann muss man nicht erst wieder von dort weg navigieren.

**Comment by alex-praschek** [comment]
An welche E-Mail soll ich das senden?

**Comment by skyrun2001** [comment]
info@remedymatch.io oder du verlinkst das einfach auf das extra angelegte Kontakt Formular. /kontakt ist dafür die Route

**Comment by alex-praschek** [comment]
Möchtest du einen vordefinierten Text oder reicht der Titel "Fehlende Kategorie" und die E-Mail?

**Comment by skyrun2001** [comment]
Ich denke fehlende Kategorie und dann die email sieht ganz nett aus

**Comment by alex-praschek** [comment]
Erledigt
