### ISSUE TITLE
Fehlermeldung bei leeren Feldern prüfen

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#13]
![image](https://user-images.githubusercontent.com/59117040/78371190-e807fa00-75c7-11ea-9554-1b2459ccc59f.png)

Diese Fehlermeldung ist denke ich nicht richtig, wenn Felder leer sind. Beim  Standort funktioniert die Fehlermeldung korrekt.

**Comment by alex-praschek** [comment]
Wird alles geprüft
