### ISSUE TITLE
Auch bei Bedarf oder Angebot die Möglichkeit des löschens anbieten

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#14]
![image](https://user-images.githubusercontent.com/59117040/78371499-59e04380-75c8-11ea-9460-0af3fe89b2e9.png)

Kann man hier und auch bei Bedarf vielleicht zusätzlich noch die Möglichkeit anbieten, dass dort eigene Einträge gelöscht oder Bearbeitet werden können?

**Comment by alex-praschek** [comment]
Eigene Bedarfe oder Angebote können auf der Startseite gelöscht werden. Bearbeitung ist noch nicht möglich

**Comment by alex-praschek** [comment]
Ich finde das ist so in Ordnung, falls da noch Einwände kommen, nochmal öffnen
