### ISSUE TITLE
Ändern der DropDown Box

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#15]
![](https://files.slack.com/files-pri/T010JAZDUA2-F0112S7DWTV/image.png)
 
Soll heißen: Name

**Comment by alex-praschek** [comment]
Das Bild funktioniert nicht

**Comment by skyrun2001** [comment]
Moment

**Comment by skyrun2001** [comment]
![image](https://user-images.githubusercontent.com/59117040/78374817-3b7c4700-75cc-11ea-85e1-02a6a45d960e.png)

**Comment by alex-praschek** [comment]
Gilt das trotz der neuen Variante noch?
Soll es Kategorie > Name > Variante heißen statt Kategorie > Aritkel > Variante?

**Comment by skyrun2001** [comment]
Ich habe das mit den neuen Kategorien noch nicht getestet

**Comment by alex-praschek** [comment]
Ist auch noch nicht deployt ;)

**Comment by alex-praschek** [comment]
Und?

**Comment by skyrun2001** [comment]
Hat geklappt :D
