### ISSUE TITLE
Datums Picker

### ISSUE THREAD

**Issue by vMarkus** [remedyMatch/rm-frontend#16]
manuelle Datumseingabe mit Zahlen nicht möglich, es MUSS der Picker genutzt werden. Zusätzlich erlaubt der Picker nur monatsweises Scrollen - bei lange haltbaren Artikeln muss ewig geklickt werden.

<img width="543" alt="Screenshot 2020-04-07 at 13 14 50" src="https://user-images.githubusercontent.com/44782615/78663314-2e17d300-78d2-11ea-9e15-5924e98c8bbd.png">

Wünsche:
- Hilfreich wäre hier händische Zahleneingabe, z. b. 7.4.2021 zusätzlich zum picker
- Picker "Jahre" vorwärts/rückwärts zusätzlich zu Monaten ermöglichen. Andere Picker machen << für Jahre, < für Monat (bzw >> und >)

**Comment by alex-praschek** [comment]
Beides gefixt
