### ISSUE TITLE
Datenprüfung "Standorte"

### ISSUE THREAD

**Issue by vMarkus** [remedyMatch/rm-frontend#17]
Eingaben werden nicht überprüft, RegEx/Java etc aus der initialen Registrierung wiederverwendbar für PLZ und weitere Daten.

Screenshot anbei
<img width="507" alt="Screenshot 2020-04-07 at 13 13 37" src="https://user-images.githubusercontent.com/44782615/78663592-b26a5600-78d2-11ea-8017-22ad88144035.png">

**Comment by vMarkus** [comment]
Update: Hauptstandort wird auch nicht überprüft bei Eingabe (Markus S. ansprechen bzw siehe Profil)

Geo Matching dann natürlich auch nicht sinnvoll möglich
<img width="227" alt="Screenshot 2020-04-07 at 14 46 27" src="https://user-images.githubusercontent.com/44782615/78670820-a4223700-78de-11ea-97c4-3736701f7c09.png">

**Comment by alex-praschek** [comment]
Ich weiß, das ist nur leider ein Problem mit dem Service, den wir im Backend angebunden haben. Vielleicht sollten wir da Google Maps einbinden. Kann aber im Frontend nicht behoben werden, bitte ans Backend adressieren.
