### ISSUE TITLE
Behelfs-Maske kann als "medizinisch" kategorisiert werden

### ISSUE THREAD

**Issue by vMarkus** [remedyMatch/rm-frontend#18]
rechtlich problematisch, medizinisch muss für die Behelfs-Masken ausgeschlossen werden? #legal chat, ebenfalls "Schutz" bei den Behelfsmasken problematisch

**Comment by alex-praschek** [comment]
Hab ich im Frontend berücksichtigt, falls das Backend medizinischAuswählbar = false liefert, wird die Checkbox deaktiviert. Das Backend liefert bisher aber IMMER true -> das muss dringend gefixt werden! Außerdem muss auch der Request, den ich sende, korrekt geprüft werden.

Danach bitte nochmal testen und erneut öffnen, falls der Fehler noch auftritt.

@matusmala @dominikhorn93

**Comment by matusmala** [comment]
War Fehler in Import Skript. Korrigiert und nochmal die Daten importieren. Danach sollte es funktionieren.

**Comment by alex-praschek** [comment]
Funktioniert
