### ISSUE TITLE
Es ist nicht eindeutig, wie man das Modal schließt

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#21]
![image](https://user-images.githubusercontent.com/59117040/78819866-3148b700-79d7-11ea-81c1-2ce94ebee506.png)

Es wäre gut oben ein x oder sowas einzubauen und man nicht nur über Abbrechen das Formular klein zu machen.

**Comment by skyrun2001** [comment]
Dies ist bei allen Modals noch der Fall

**Comment by alex-praschek** [comment]
Ich finde es eigentlich relativ intuitiv... kann man machen, falls ihr das unbedingt wollt, ist aber meiner Meinung nach ziemlich standard in der IT-Welt.

Man kann auch daneben klicken, um den Dialog zu schließen, das hab ich aber deaktiviert, um Datenverlust vorzubeugen, wenn man versehentlich dorthin klickt.

**Comment by skyrun2001** [comment]
Ja okay da hast du recht, dass ist schon intuitiv. Dann lassen wir es.

**Comment by roman-1983** [comment]
Funktion bleibt so bestehen.
