### ISSUE TITLE
Favicon ersetzen durch das RemedyMatch favicon

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#22]
![image](https://user-images.githubusercontent.com/59117040/78820048-766ce900-79d7-11ea-8fba-bbcbacee8046.png)
 
Das Favicon bitte durch diese Image ersetzen.

![rememdy-match-icon](https://user-images.githubusercontent.com/59117040/78820194-addb9580-79d7-11ea-98a4-a943142d78a0.png)

**Comment by alex-praschek** [comment]
Erledigt
