### ISSUE TITLE
Artikel Varianten sind nicht sortiert

### ISSUE THREAD

**Issue by hauptmedia** [remedyMatch/rm-frontend#23]
<img width="758" alt="Bildschirmfoto 2020-04-13 um 16 31 20" src="https://user-images.githubusercontent.com/10770719/79128887-86ecdd00-7da4-11ea-83c7-7878affb69aa.png">

**Comment by alex-praschek** [comment]
Wer gibt die Sortierung vor? S/M/L ist ja nicht gerade alphabetisch...

**Comment by hauptmedia** [comment]
Hier muss wohl backend noch ein Feld für die Sortierung einbauen

**Comment by alex-praschek** [comment]
Funktioniert jetzt
