### ISSUE TITLE
Wenn "Produkt ist medizinisch" nicht verfügbar ist, muss auch die checkbox unchecked werden

### ISSUE THREAD

**Issue by hauptmedia** [remedyMatch/rm-frontend#24]
<img width="267" alt="Bildschirmfoto 2020-04-13 um 16 34 59" src="https://user-images.githubusercontent.com/10770719/79129049-cfa49600-7da4-11ea-8ca9-d99f740e2470.png">

**Comment by alex-praschek** [comment]
Klappt
