### ISSUE TITLE
Angebot - Email: Kategorie nicht vorhanden

### ISSUE THREAD

**Issue by vMarkus** [remedyMatch/rm-frontend#28]
# Ausgangssituation
<img width="587" alt="Screenshot 2020-04-14 at 15 34 09" src="https://user-images.githubusercontent.com/44782615/79230833-7c464c80-7e65-11ea-8227-0b25da75faea.png">

# Beschreibung 
Verlinkung zu mailto:<emailadresse> im Text "Kategorie oder Artikel nicht gefunden? Schreib uns eine E-Mail!" unterhalb von "Artikel"

# Akzeptanzkriterien
Text als mailto: Link hinterlegen, damit per klick die neue Kategorie per Email an die von uns gewählte Adresse/Verteiler geschickt wird zum Nachpflegen

**Comment by alex-praschek** [comment]
Das ist bereits umgesetzt - nur nicht deployt bisher
https://github.com/remedyMatch/rm-frontend/blob/master/src/screens/Dialogs/Demand/AddDemandDialog.tsx#L227
