### ISSUE TITLE
Bedarf - Email: Kategorie nicht vorhanden

### ISSUE THREAD

**Issue by vMarkus** [remedyMatch/rm-frontend#29]
identisch zu Issue für Angebot, nur hier mit dem Bezug auf Bedarf: https://github.com/remedyMatch/rm-frontend/issues/28

mailto: link hinterlegen, Details siehe https://github.com/remedyMatch/rm-frontend/issues/28

**Comment by alex-praschek** [comment]
Ebenfalls wie dort: bereits umgesetzt, nicht deployt:
https://github.com/remedyMatch/rm-frontend/blob/master/src/screens/Dialogs/Demand/AddDemandDialog.tsx#L227
