### ISSUE TITLE
Anzahl darf 0 sein

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#32]

**Comment by alex-praschek** [comment]
Bisschen genauer? Welche Anzahl? Bei Bedarf und Angebot einstellen wird darauf geprüft. Ich weiß nicht, was du meinst

**Comment by skyrun2001** [comment]
Achso okay, dann war das ein Problem, dass der Kommentar diesen Fehler überschrieben hat, sorry
