### ISSUE TITLE
Vorangestellte 0 in Anzahl nicht löschbar

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#33]

**Comment by skyrun2001** [comment]
Die Anzahl ist mit 0 befüllt, diese kann man aber nicht löschen

**Comment by alex-praschek** [comment]
Bei Angebot und Bedarf anlegen ist es gefixt. Da leider nicht genau dran steht, welche 0 du meinst, kann ich nicht mehr machen. Falls es noch woanders auftritt, bitte neuen Issue erstellen.
