### ISSUE TITLE
Kommentar ist ein Pflichtfeld

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-frontend#34]

**Comment by skyrun2001** [comment]
Ein Kommentar ist doch eher optional oder?

**Comment by alex-praschek** [comment]
Der Meinung würde ich mich anschließen, aber im Backend ist die Validierung aktiviert, dass der Kommentar nicht leer sein darf. D.h. wenn ich die Warnung entferne, fliegt halt ein 400er Fehler im Backend. Bitte bei Bedarf im Backend anpassen und neuen Issue anlegen.
