### ISSUE TITLE
Kontaktformular der Website verlinken

### ISSUE THREAD

**Issue by scriptibus** [remedyMatch/rm-frontend#36]
Das Kontaktformular ist unter https://remedymatch.io/#contact-anchor zu finden

**Comment by alex-praschek** [comment]
Und wo soll ich das verlinken?

**Comment by scriptibus** [comment]
@hauptmedia  ping?

**Comment by hauptmedia** [comment]
Anstatt diese mailto: Links wenn eine Kategorie fehlt ein Link auf's Kontaktformular. Am besten target="_blank" damit sich nicht die Anwendung beendet

**Comment by alex-praschek** [comment]
Erledigt
