### ISSUE TITLE
Bedarf anlegen - Eingabemaske anpassen

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-frontend#4]
Die 3 Eingabefelder/Checkboxen sind für einen Bedarf nicht erforderlich und sollen entfernt werden.
Die Felder sind nur für ein Angebot erforderlich.

![image](https://user-images.githubusercontent.com/3573021/77423684-0ef84c00-6dd0-11ea-957f-17948e4bc2f2.png)

**Comment by alex-praschek** [comment]
Hab ich entfernt, wird gleich deployt
