### ISSUE TITLE
Bedarf erstellen - Artikel sind doppelt

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-frontend#5]
Im Feld "Artikel" sind einige Artikel doppelt. Lässt sich dieses einfach zusammenführen?

![image](https://user-images.githubusercontent.com/3573021/77423796-4666f880-6dd0-11ea-86da-c70b1cfdb8f2.png)

**Comment by alex-praschek** [comment]
Im Frontend wird nur die Liste angezeigt, wie sie vom Backend kommt. Vermutlich gibt es die im Moment einfach noch mehrfach. Da sollte man bei Gelegenheit aufräumen.
