### ISSUE TITLE
Angebote Liste

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-frontend#6]
# Fachliche Beschreibung
In der Liste der Angebote wird die Institution angezeigt. Aus Datenschutzgründen soll dies in der Liste nicht angezeigt werden.
![image](https://user-images.githubusercontent.com/3573021/77423903-862de000-6dd0-11ea-83a3-285219fd5722.png)

# Technische Beschreibung
- Ausblenden der Institution in der Liste

# Akzeptanzkriterien
- Beim Anzeigen der Angebots-Liste wird die Institution nicht angezeigt
- Beim Anzeigen der Angebots-Liste wird der Ort weiterhin angezeigt

**Comment by alex-praschek** [comment]
Ist erledigt, es wird nur noch der Standort selbst angezeigt. Ich gebe aber zu Bedenken, dass die Daten selbst trotzdem im Browser vorhanden sind und nur nicht angezeigt werden. Ein versierter Anwender kann sie trotzdem auslesen, indem er die Entwicklertools verwendet.

**Comment by alex-praschek** [comment]
@matusmala @dominikhorn93

**Comment by matusmala** [comment]
Was heißt es ? Daten aus REST Entfernen?

**Comment by alex-praschek** [comment]
Ja, oder maskieren (mit ** oder ähnlichem)
