### ISSUE TITLE
Angebot - Details

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-frontend#7]
# Fachliche Beschreibung
In der Detailansicht eines Angebots wird der Anbieter angezeigt. Aus Datenschutzgründen soll dies  nicht angezeigt werden.
![image](https://user-images.githubusercontent.com/3573021/77424068-cf7e2f80-6dd0-11ea-9685-627a3f5799a1.png)

# Technische Beschreibung
- Ausblenden des Felds "Anbieter"

# Akzeptanzkriterien
- Beim Anzeigen der Angebots-Details wird der Anbieter nicht angezeigt
- Beim Anzeigen der Angebots-Details wird der Ort weiterhin angezeigt

**Comment by alex-praschek** [comment]
Es wird nur noch der Standort angezeigt. Allerdings selbes Problem wie in #6
