### ISSUE TITLE
Institution - umbenennen

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-frontend#8]
# Fachliche Beschreibung
Der Menüeintrag "Institution" ist verwirrend und soll umbenannt werden. Besser wäre die Bezeichnung "Mein Konto". Außerdem sollen einige Felder für den Benutzer ausgeblendet werden.

![image](https://user-images.githubusercontent.com/3573021/77424353-3ef41f00-6dd1-11ea-9476-13bedd0a37ca.png)

# Technische Beschreibung
- Umbennung des Menüeintrag "Institution" in "Mein Konto"
- Entfernen des Felds "Institution-ID"
- Entfernen des Feld "Institution-Key"
- Die ausgeblendeten Felder können für die Admin-Rolle weiterhin sichtbar sein

**Comment by alex-praschek** [comment]
Ist erledigt, das mit der Admin-Rolle erstmal nicht, da wir noch nicht soweit sind. Zudem ist das natürlich nur eine kosmetische Änderung, in der URL bspw. steht noch Institution.

**Comment by alex-praschek** [comment]
URL ist ebenfalls gefixt
